# Copyright 2025 CIQ, Inc. All rights reserved.

{{- $root := "/fuzzball" }}
{{- $port := (randInt 10000 30000) }}

{{- if not (trim .Volumes | hasPrefix "volume://") }}
  {{-  fail "At least one volume has to be specified in the Volumes field." }}
{{- end }}
{{- $volumes := splitList "," .Volumes }}

version: v1
volumes:
{{- range $i, $v := $volumes }}
  vol-{{ $i }}:
  {{- $parts := (splitList ":" $v) }}
  {{- if eq (len $parts) 2 }}
    reference: {{ $v }}
  {{- else if eq (len $parts) 3 }}
    reference: {{ index $parts 0 }}:{{ index $parts 1 }}
  {{- else }}
    {{- fail (printf "Invalid volume reference: %s" $v) }}
  {{- end }}
{{- end }}

services:
  cloudcmdr:
    image:
      uri: {{ .Container }}
    resource:
      cpu:
        cores: 1
      memory:
        size: 6GiB
    cwd: /fuzzball
    env:
      - HOME=/tmp/cloudcommander
    export: workflow
    persist: true
    network:
      ports:
        - name: web
          port: {{ $port }}
          protocol: tcp
      endpoints:
        - name: file-browser
          port-name: web
          type: path
          protocol: http
          scope: {{ .ServiceScope }}
    mounts:
{{- range $i, $v := $volumes }}
  {{- $parts := splitList ":" $v }}
  {{- if eq (len $parts) 2 }}
      vol-{{ $i }}:
        location: {{ $root }}/{{ trimPrefix "volume://" $v }}
   {{- else }}
      vol-{{ $i }}:
        location: {{ $root }}/{{ index $parts 2 | trimPrefix "/" }}
   {{- end}}
{{- end }}

    script: |
      #!/bin/sh
      mkdir -p "${HOME}"
      cat <<__EOF__ > "${HOME}/.cloudcmd.menu.js"
      export default {
          'R - cd /': async ({CloudCmd}) => {
              await CloudCmd.changeDir('/');
          },
          'X - Exit the File Browser': async ({CloudCmd}) => {
              const {Dialog, CurrentInfo, TerminalRun} = DOM;
              const [cancel] = await Dialog.confirm("Exit Cloud Commander?");
              if (cancel) {
                  return;
              }
              CloudCmd.TerminalRun.show({
                command: 'bash -c "p=\$(cat ${HOME}/.cloudcmd.pid); kill \$p; while kill -0 \$p &> /dev/null; do sleep 1 ; done"',
                autoClose: true,
                cwd: "/tmp"
              });
              window.setTimeout(() => {
                try {
                  document.querySelectorAll('.terminal').forEach(el => el.remove());
                  CloudCmd.View.hide();
                  document.body.innerHTML = '<h1>Cloud Commander has exited</h1><p>You can close this tab. The Fuzzball service will end automatically</p>';
                  document.title = 'Session Ended';
                } catch (e) {}
              }, 2000);

          },
      }
      __EOF__

      /usr/src/app/bin/cloudcmd.mjs \
        --port {{ $port }} \
        --prefix "${FB_ENDPOINT_PATH}" \
        --name "Fuzzball Cloud Commander" \
        --keys-panel \
        --config-dialog \
        --root {{ $root }} \
        --terminal &
      echo $! > ${HOME}/.cloudcmd.pid
      wait
      exit 0
